### ISSUE TITLE
Support applying server middlewares

### ISSUE THREAD

**Issue by glennreyes** [glennreyes/graphpack#11]
We need to be able to import the server instance to apply middlewares on it.

For example, in `src/config.js` adding following:

```js
import { server } from 'graphpack';

server.applyMiddleware(/* ... */);
```

More details about applying middlewares in the [Apollo Server docs](https://www.apollographql.com/docs/apollo-server/api/apollo-server.html#ApolloServer-applyMiddleware).

**Comment by farskid** [comment]
@glennreyes For this to happen, we need to expose a start mechanism instead of auto starting the server. This way user can start the server on demand once all the middlewares are applied.

This also scales well for other server properties we might need to support later.

**Comment by glennreyes** [comment]
@farskid Yep exactly. I'm okay with that as long as we don't have to do it when there's no middleware set up. Any idea or preference how to design that api? Currenty thinking of:

```js
// src/config.js
export default {
  applyMiddleware: { app },
  introspection: true,
  playground: true, 
}
```

**Comment by farskid** [comment]
@glennreyes I think it's good as it matches with Apollo docs. I'm up with consistency too.

**Comment by rustamli** [comment]
@farskid  @glennreyes have you guys tested this? can't get it working 

this is my **graphpack.config.js**:

```javascript
const express = require('express');
const app = express();

app.get('/version', (req, res) => {
  res.send('hello world');
});


module.exports = (mode) => {
  const IS_DEV = mode !== 'production';
  return {
    server: {
      introspection: IS_DEV,
      playground: IS_DEV,
      applyMiddleware: { app }
    }
  }
};
```

It ends up with following error:

```
(node:14783) UnhandledPromiseRejectionWarning: ReferenceError: applyMiddleware is not defined
    at startServer (/Users/turan/gh/getguided-unicorn/build/index.js:273:28)
    at <anonymous>
(node:14783) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled w
ith .catch(). (rejection id: 1)
(node:14783) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I think something might be wrong with this line: 

https://github.com/glennreyes/graphpack/blob/a3a61f8745748691f56b4d77bc720ba84d2c4bcc/packages/graphpack/lib/server.js#L45

Or am I doing something wrong in my config?
