### ISSUE TITLE
Integration with existing Express app ?

### ISSUE THREAD

**Issue by revskill10** [glennreyes/graphpack#14]
Is it possible to integrate the package with an existing express.js application ?

**Comment by revskill10** [comment]
@farskid I'm using NextJS. It uses `next dev` and `next build` for development, but graphpack uses different command to develop. It's my main concern to integrate both in development.

**Comment by farskid** [comment]
@glennreyes Any thoughts in terms of integration with Next?

**Comment by glennreyes** [comment]
This was meant to be a standalone app. But of course, if someone has an idea to make it integrating with next.js nicely please let us know!

Adding middlewares should be available soon with #20.
