### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by glennreyes** [glennreyes/graphpack#23]
Not a high prio, but highly appreciated if someone feels like designing a logo for Graphpack.

**Comment by nenjotsu** [comment]
@glennreyes yow there, I made this logo for your graphpack, let me know if like or not

![graphpack-logo](https://user-images.githubusercontent.com/26914800/47516509-333cba00-d8b8-11e8-90df-4aab72ed9d96.png)

**Comment by nenjotsu** [comment]
@glennreyes - yes, of course. I have made changes in figma logo study, https://www.figma.com/file/XyKbNTDI9lwoJNr91l91bQ7C/Graphpack let me know your feedback, thanks

**Comment by richardbmx** [comment]
@glennreyes  Hello I see that you are looking for a logo I would like to present my proposal of a logo for your project. is based on representing a box to give your project its own identity

![logo117](https://user-images.githubusercontent.com/35604837/47667572-b3934180-db7c-11e8-995e-2bdded73e24f.png)

**Comment by glennreyes** [comment]
@richardbmx This is peeerrrfect, thanks for that! What's the font? If it's fine for using in OSS, then let's go with this 👍.

If you could add all of the variations into the Figma project that would be great. Other than that, I'd say let's replace the title in the README with that.

**Comment by richardbmx** [comment]
@glennreyes  I can generate a google folder with all the necessary files and the different variations to use the logo

**Comment by richardbmx** [comment]
@glennreyes  Here you can find a Google folder with all the necessary files to use the logo, find different variations in different formats and also open a file that grants all the rights for free use.

[Google Drive](https://drive.google.com/open?id=1OMMHf19icKlG2bWJNtQtCGxDw84JHKsV)

**Comment by glennreyes** [comment]
Thanks @richardbmx, appreciate your work! Two things:
- Can you tell what font you have used?
- What do you think of a version with all the dots connected?

**Comment by richardbmx** [comment]
[FONT NEXA](https://www.behance.net/gallery/4628581/NEXA-free-)

What do you mean by all the points attached?

**Comment by glennreyes** [comment]
@richardbmx Like this: 
![image](https://user-images.githubusercontent.com/5080854/47675434-3e466180-dbba-11e8-95eb-48a0c8bc0ad3.png)

**Comment by richardbmx** [comment]
@glennreyes  I did not want to do it that way so that it was not so common the intention of doing it the way I did it was that it was different to the GraphQL logo but at the same time it had a relationship and it was unique for your project

**Comment by richardbmx** [comment]
In the same way, if you want, I can do it like that

**Comment by glennreyes** [comment]
@richardbmx that would be awesome! Although I like your initial version I got some feedback that it was looking similar to a swastika. Hopefully we find a way to prevent this 👍

**Comment by richardbmx** [comment]
@glennreyes  I present the logotypi with the variant of showing all points together

![logo11722](https://user-images.githubusercontent.com/35604837/47745173-72bd2a80-dc59-11e8-919c-29a00369da6a.png)

**Comment by glennreyes** [comment]
That's great @richardbmx! I think removing the middle dot was a perfect move to make it look more like a "packet". What do you think?

Would you mind dragging the SVG into https://www.figma.com/file/XyKbNTDI9lwoJNr91l91bQ7C/Graphpack?

**Comment by glennreyes** [comment]
If that's all fine I'll take care of creating a PR adding all this into the README.md. Also if you don't mind I'll put you into the acknowledgement section 😉

**Comment by richardbmx** [comment]
I can generate all the files in the same google drive folder
